### ISSUE TITLE
Theme 7 th in tbody missing background colour reset

### ISSUE THREAD

**Issue by mrginglymus** [cambridgeuniversity/Project-Light#82]
https://github.com/cambridgeuniversity/Project-Light/blob/master/stylesheets/full-stylesheet.css#L2278

needs theme-7 reset. Looks like  line 2245 and 2270 are also missing something like this.

**Comment by tombsar** [comment]
This was almost fixed in c9e7a32c15b156b2a681a0cfe0f3a06304a93c30, just one more rule needed updating.
