### ISSUE TITLE
No link icon for Powerpoint files

### ISSUE THREAD

**Issue by tombsar** [cambridgeuniversity/Project-Light#86]
The theme contains icons and associated css styles for hyperlinks to download PDF files, Excel spreadsheets, and Word documents. However, there is no such icon for Powerpoint presentations. Would it be possible to add an option for this type of link?

**Comment by barneybrown** [comment]
Yes. I’m going to see if the design team can source something.

Barney

**Comment by tombsar** [comment]
It looks like this has been added in 54032d4c589d4c092cf51848346d5ac34d2e95cb. Thanks!
