### ISSUE TITLE
No LICENSE file or contribution guide

### ISSUE THREAD

**Issue by tombsar** [cambridgeuniversity/Project-Light#87]
The current README document is minimal, and there's no information (that I can see) about copyright or terms of usage of the templates. The fact that you've put it up on GitHub gives a presumption of "open-source"-ness, but are users free to fork and make changes? Can it be used by people not attached to the university? Do you welcome issues and pull requests, or is this more of a code dump than a living repository? These are just a few questions off the top of my head that it would be good to get in writing somewhere to avoid misunderstandings in future.

Thanks!

**Comment by barneybrown** [comment]
These templates are only for use by people building websites for the University of Cambridge.
This is a code dump at the moment, and will ultimately be superseded by a pattern library (as opposed to a set of templates). Production on those hasn't started yet, and will happen in the University's Gitlab.

Happy to meet up and talk through more of the background to how we got here, are you based at Engineering?

**Comment by tombsar** [comment]
Happy to talk offline. I'll email you!
