### ISSUE TITLE
PHP errors: Declaration of Walker_Nav_Menu_Dropdown should be compatible with Walker_Nav_Menu

### ISSUE THREAD

**Issue by orion434** [cambridgeuniversity/Project-Light#90]
I receive multiple log entry caused by some incompatible declaration between `Walker_Nav_Menu_Dropdown ` and  `Walker_Nav_Menu`:

```
Declaration of Walker_Nav_Menu_Dropdown::end_el() should be compatible with 
Walker_Nav_Menu::end_el(&$output, $item, $depth = 0, $args = Array)

Declaration of Walker_Nav_Menu_Dropdown::start_el() should be compatible with 
Walker_Nav_Menu::start_el(&$output, $item, $depth = 0, $args = Array, $id = 0)

Declaration of Walker_Nav_Menu_Dropdown::end_lvl() should be compatible with
Walker_Nav_Menu::end_lvl(&$output, $depth = 0, $args = Array)

Declaration of Walker_Nav_Menu_Dropdown::start_lvl() should be compatible with 
Walker_Nav_Menu::start_lvl(&$output, $depth = 0, $args = Array)

Type: PHP Strict Standards Line: 0
File: 
/wp-content/plugins/Project-Light-Core-Functionality-ACF-master/inc/nav-menu-dropdown.php
```

**Comment by andybatey** [comment]
The incompatible declaration between Walker_Nav_Menu_Dropdown and Walker_Nav_Menu is a WordPress issue and your reference to Advanced Custom Fields (ACF) suggests this relates to the Clinical School Computing Service implementation of this Project Light reference.

This is not an issue with this repository, which is a reference implementation of Project Light, but with a WordPress implementation of Project Light and the issue should be raised against that.

**Comment by orion434** [comment]
Thank you for the clarification.

**Comment by orion434** [comment]
I fixed the issue looking at the code. Do you have any reference url or contact where I can sed the fix? (I was not able to find online the same repository that is installed, "Core Functionality version 2", v2.06 )

**Comment by andybatey** [comment]
The only information I have is the URL http://websupport.cscs.medschl.cam.ac.uk/wordpress/download-the-project-light-theme-for-wordpress/

Andy Batey
Drupal System Developer
UIS, University of Cambridge
